### ISSUE TITLE
Let me know if you need help with using Git and GitHub

### ISSUE THREAD

**Issue by aaronfranke** [carykh/testRepository#7]
@carykh 

I recommend GitKraken https://www.gitkraken.com/ It's a great GUI Git client that shows changes and branches [visually](https://i.imgur.com/Jdi5zVL.png), allows dragging branches onto each other for various operations.

**Comment by wooden-utensil** [comment]
Yeah Cary knife holder, oh wait, kitten hugger, oh wait!

**Comment by aaronfranke** [comment]
I'll close this, if you do need help check out https://www.youtube.com/watch?v=0XKy8YpP5Ww
